{% set name = "tpot2" %}
{% set version = "0.1.6a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TPOT2-{{ version }}.tar.gz
  sha256: 864332d16ef056b01fe4c4d539afe1c112eb92364f31d966c48c3278a870d788

build:
  entry_points:
    - tpot2=tpot2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy >=1.16.3
    - scipy >=1.3.1
    - scikit-learn >=1.2.0
    - update_checker >=0.16
    - tqdm >=4.36.1
    - stopit >=1.1.1
    - pandas >=1.5.3,<2.0.0
    - joblib >=1.1.1
    - xgboost >=1.7.0
    - matplotlib-base >=3.6.2
    - traitlets >=5.8.0
    - lightgbm >=3.3.3
    - optuna >=3.0.5
    - baikal >=0.4.2
    - jupyter >=1.0.0
    - networkx >=3.0
    - dask-core >=2023.3.1
    - distributed >=2023.3.1
    - dask-ml >=2022.5.27
    - dask-jobqueue >=0.8.1
    - func_timeout >=4.3.5

test:
  imports:
    - tpot2
  requires:
    - pip

about:
  home: https://github.com/EpistasisLab/tpot2
  summary: Tree-based Pipeline Optimization Tool
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jay-m-dev
    - nickotto
    - perib
    - epistasislab
