{% set name = "tpot2" %}
{% set version = "0.1.6a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TPOT2-{{ version }}.tar.gz
  sha256: 59c9f1fa8b3c821876bc88fdec885d01d593479674ea607ef1aae529d63b47da

build:
  entry_points:
    - tpot2=tpot2:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  host:
    - baikal >=0.4.2
    - configspace >=0.7.1
    - dask >=2024.4.2
    - dask-expr >=1.0.12
    - dask-jobqueue >=0.8.5
    - distributed >=2024.4.2
    - func_timeout >=4.3.5
    - joblib >=1.1.1
    - lightgbm >=3.3.3
    - matplotlib >=3.6.2
    - networkx >=3.0
    - numpy >=1.26.4
    - optuna >=3.0.5
    - pandas >=2.2.0
    - pip
    - python
    - scikit-learn >=1.3.0
    - scipy >=1.3.1
    - stopit >=1.1.1
    - tqdm >=4.36.1
    - traitlets >=5.8.0
    - update_checker >=0.16
    - xgboost >=1.7.0
  run:
    - baikal >=0.4.2
    - configspace >=0.7.1
    - dask >=2024.4.2
    - dask-expr >=1.0.12
    - dask-jobqueue >=0.8.5
    - distributed >=2024.4.2
    - func_timeout >=4.3.5
    - joblib >=1.1.1
    - lightgbm >=3.3.3
    - matplotlib >=3.6.2
    - networkx >=3.0
    - numpy >=1.26.4
    - optuna >=3.0.5
    - pandas >=2.2.0
    - python
    - scikit-learn >=1.3.0
    - scipy >=1.3.1
    - stopit >=1.1.1
    - tqdm >=4.36.1
    - traitlets >=5.8.0
    - update_checker >=0.16
    - xgboost >=1.7.0

test:
  imports:
    - tpot2
  requires:
    - pip

about:
  home: https://github.com/EpistasisLab/tpot2
  summary: Tree-based Pipeline Optimization Tool
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jay-m-dev
    - nickotto
    - perib
    - epistasislab
